#!/usr/bin/env python
"""
Build <results_dir>/qualitative/INDEX.md from the README.md front matter of every evaluation folder.

Each qualitative delivery is a folder `<results_dir>/qualitative/<topic>-<MM-DD>/` whose
README.md starts with a YAML block:

    ---
    title: Ear heatmaps on IBL
    date: 2026-09-18
    data_version: head-fixed-v2
    question: Why do the ear channels fire on paws?
    models: trunks/face+...; dedicated/hantman-mv
    outputs: ear_heatmaps_ibl.mp4, stats.csv
    finding: one sentence
    ---

    python scripts/qualitative_index.py            # current results_dir
    python scripts/qualitative_index.py --results_dir <path>
"""

import argparse
from pathlib import Path

import yaml

from mouse_pose.paths import load_paths


def front_matter(readme: Path) -> dict | None:
    text = readme.read_text()
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    return yaml.safe_load(text[3:end]) if end > 0 else None


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1], epilog=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--results_dir", type=Path, default=Path(load_paths()["results_dir"]))
    args = ap.parse_args()
    q = args.results_dir / "qualitative"
    rows, missing = [], []
    for d in sorted(q.glob("*/")):
        fm = front_matter(d / "README.md") if (d / "README.md").exists() else None
        (rows if fm else missing).append((d.name, fm))
    lines = [f"# Qualitative evaluations — {args.results_dir.name}", "",
             "Generated by `scripts/qualitative_index.py` from each folder's README front matter; edit the",
             "READMEs, not this file.", "", "| folder | date | question | models | finding | outputs |", "|---|---|---|---|---|---|"]
    for name, fm in rows:
        g = lambda k: str(fm.get(k, "")).replace("|", "\\|").replace("\n", " ")
        lines.append(f"| [`{name}`]({name}/README.md) | {g('date')} | {g('question')} | {g('models')} | {g('finding')} | {g('outputs')} |")
    if missing:
        lines += ["", "Folders without a README front matter (add one): " + ", ".join(f"`{n}`" for n, _ in missing)]
    (q / "INDEX.md").write_text("\n".join(lines) + "\n")
    print(f"{len(rows)} indexed, {len(missing)} without front matter -> {q / 'INDEX.md'}")


if __name__ == "__main__":
    main()
