exclude:
  keypoints:
    - earroot
    - earlateral
    - eartip
    - lickport
    - noseright
  sessions:

keypoints:
  eyelateral: eye_back_{side}
  eyemedial: eye_front_{side}
  lowerjaw: lowerlip
  nosebottom: nose_bottom
  noseroot: nose_top
  nosetip: nose_tip
  tonguetip: tongue_tip
  rightpawcenter: wrist_right
  leftpawcenter: wrist_left

sessions:
  iter1_images: right
  iter2_images: right
  iter3_images: right
  iter4_images: right
  iter5_images: right
  iter6_images: right
